### ISSUE TITLE
does it support version 2.x?

### ISSUE THREAD

**Issue by rezam90** [ambelovsky/gosf#1]
Hey @ambelovsky.
Is it production ready?
Does it support socketio v2?

**Comment by ambelovsky** [comment]
Yes, SocketIO v2 is supported by this framework.  In all of the examples, I use SocketIO v2 to connect to the server.

This project is new, so it is not yet production ready.  However, I'm very active on the project, and I'm able to address bugs quickly.

**Comment by ambelovsky** [comment]
Documentation has now been updated with socket.io v2 callout.
