### ISSUE TITLE
gosf client?

### ISSUE THREAD

**Issue by eugbyte** [ambelovsky/gosf#15]
is there is any way to use the is library to connect as socket-io client for a socket io server?

**Comment by ambelovsky** [comment]
Please see: http://gosf.io/#consuming-a-microservice

**Comment by eugbyte** [comment]
Is "endpoint" the same as the event name, or does it refer to the namespace?

```
// Listen on an endpoint
gosf.Listen("echo", echo)
```

I am trying to use gosf to listen to a socketio Node.js server, but I am getting `error: Timeout`
