### ISSUE TITLE
Project Status?

### ISSUE THREAD

**Issue by ASoldo** [ambelovsky/gosf#18]
Hi, I have accidentally found this repo and implemented it inside my demo app and it works great. But gotta ask is this project over/abandoned/done? I am just curious since it's a long time from last update and I do like how it behaves.
Thank you!

**Comment by ambelovsky** [comment]
Good question.  I am still monitoring and merging pull requests anytime someone contributes, but I haven't contributed much to this project myself in quite a while.  I also actively maintain the website.  I'm open to new pull requests anytime.
