### ISSUE TITLE
How to get query parameters ? Is this package updated?

### ISSUE THREAD

**Issue by ezewu** [ambelovsky/gosf#4]

**Comment by ambelovsky** [comment]
Hello Mr. Wu,

Yes, this package was updated. New configuration options were added.

rejectInvalidHostnames (false by default)
enableCORS (useless for now)

rejectInvalidHostnames now allows you to gain tighter security for TLS connections by verifying host/cert combinations. Setting this to true will guard against man in the middle attacks.

These new configuration options are documented at gosf.io.

**Comment by ambelovsky** [comment]
Regarding getting query parameters, please review the sample project and the documentation.

Documentation: http://gosf.io/#your-first-server

Sample Project: https://github.com/ambelovsky/gosf-sample-app

**Comment by mrasif** [comment]
> Regarding getting query parameters, please review the sample project and the documentation.
> 
> Documentation: http://gosf.io/#your-first-server
> 
> Sample Project: https://github.com/ambelovsky/gosf-sample-app

I want to pass some parameters on socket connection time. like token, but I didn't find anything there. Can you tell me how I can do that ?
