### ISSUE TITLE
add CORS to socket path

### ISSUE THREAD

**Issue by chatupol98int** [ambelovsky/gosf#5]
can i config CORS??
I'm a newbie for golang.

**Comment by ambelovsky** [comment]
https://github.com/ambelovsky/gosf/issues/3

Please click the link above and let me know if this solves your issue.

**Comment by chatupolDotint** [comment]
sorry,that not work for me,because my socket domain run on differrent with socket caller.
I'm not good at English.

**Comment by ambelovsky** [comment]
in your client code (docket caller), make sure you've specified that your client will only communicate over a web socket transport.

socket = io.connect(socketUri, { transports: ['websocket'] });

**Comment by ambelovsky** [comment]
Cannot use http — must use the websocket transport so that your connection does not have to upgrade from http to websocket.

**Comment by chatupolDotint** [comment]
thanks,
my socket is on heroku cloud,can you tell me to upgrade http to socket.

**Comment by ambelovsky** [comment]
Download the sample project: https://github.com/ambelovsky/gosf-sample-app

`. ./scripts/getdeps.sh`
`. ./scripts/run.sh`

Modify scaffolding.html on line 15:
`var socketUri = 'ws://localhost:9990';`

Replace "localhost" with your Heroku server IP address.
