### ISSUE TITLE
act as client

### ISSUE THREAD

**Issue by celevra** [ambelovsky/gosf#6]
Hi,

looked into the documentation and the code.
am i right that gosf can't act as an socket.io client from within go?

regards

Celevra

**Comment by ambelovsky** [comment]
Hi Celevra,

Yes. Please see http://gosf.io/#consuming-a-microservice

You can replace the request object with your own custom request type if you do not have a gosf server on the other end.

Enviado do meu iPhone

**Comment by celevra** [comment]
thank you for your fast answer.
if i'm looking in the right direction its only possible do send data to the Server not to listen for incoming messages like
```
io.on("message",function(msg) {
    console.log(msg);
})
```

**Comment by celevra** [comment]
ok my fault, i think i have to use gofs-socketio
this example works perfect, thank you!
```
https://github.com/ambelovsky/gosf-socketio/blob/master/examples/client.go
```
