### ISSUE TITLE
Client broadcast not working

### ISSUE THREAD

**Issue by sudhanshumonga** [ambelovsky/gosf#8]
As mentioned in the documentation here: http://gosf.io/#client-broadcasts
this method is broadcasting to the sender client as well. 
I am sendin socket.emit on this "Register" method of the controller on connecting: 
````
func (controller Auth) Register(client *f.Client, request *f.Request) *f.Message
 {
	response := f.NewSuccessMessage("client registered", nil)
	body := request.Message.Body
	fmt.Println(*request)
	client.Join(body["room"].(string))//this is how it works
	return response
}
````

When the client sends a message it hits the controller's this method: 
````
func (controller Chatter) SendMessage(client *f.Client, request *f.Request) *f.Message
 {
	body := request.Message.Body
	message := request.Message.Text
	room := body["room"].(string)
	fmt.Println(room)
	fmt.Println(request.Endpoint)
	response := f.NewSuccessMessage(message, body)
	client.Broadcast(room, request.Endpoint, response) // supposed to send only non-sender clients
	return nil
}
````

**Comment by sudhanshumonga** [comment]
```
socket.emit('chat', {
			id: msgData.id,
			text: msgData.text,
			body: {
				room: roomID
			}
		})
```
chat endpoint is being listened to send message to other connected clients.
Also, when id is a string, it fails to send. Please add support for string as ID.

**Comment by sudhanshumonga** [comment]
hi @ambelovsky  can you please look into this issue we need to use this lib as it has perfectly integrated because of its simplicity.

**Comment by ambelovsky** [comment]
Yes, I will take a look as soon as I can. You caught me during a vacation.

Enviado do meu iPhone

**Comment by sudhanshumonga** [comment]
@ambelovsky thanks a lot and sorry to bother you on vacay.

**Comment by ambelovsky** [comment]
Looks like we have two separate issues here:

1. Bug - Client broadcast is including the originating client in broadcast response
2. Feature Request - Add support for passing a message ID as a string

I'll take a look this week and see what I can do.  Thanks!

**Comment by ambelovsky** [comment]
Sudhanshumonga,

The bug where a client broadcast is including the originating client has now been fixed.

Please run the following to update your gosf-socketio package:

`go get -u "github.com/ambelovsky/gosf-socketio"`

**Comment by ambelovsky** [comment]
Sudhanshumonga,

You can now pass a "uuid" or "guid" instead of or in addition to "id" with your message.  "id" will continue to require an integer, but "uuid" and "guid" can accept string values.

Please update GOSF with the following:

`go get -u "github.com/ambelovsky/gosf"`

Help support ongoing development effort with a donation to the following BTC wallet: 13pkXi8bW5bKjWewQYtv36CUgwhgQEn7eA

**Comment by sudhanshumonga** [comment]
Thanks a lot ambelovsky, will check out the fix!
